/* themeUtils.js
 * UMD-style: works in browser (window.ThemeUtils) AND in Jest/Node (module.exports)
 */
(function (root, factory) {
    // Node / Jest
    // eslint-disable-next-line no-undef
    if (typeof module === "object" && module.exports) {
        // eslint-disable-next-line no-undef
        module.exports = factory();
    } else {
        // Browser / Extension
        root.ThemeUtils = factory();
    }
})(typeof self !== "undefined" ? self : this, function () {
    "use strict";

    /**
     * Options used to build a Chrome Theme manifest.
     *
     * @typedef {Object} BuildThemeOptions
     * @property {string} themeName - Display name for the theme.
     * @property {string} frameHex - Hex color for the browser frame.
     * @property {string} toolbarHex - Hex color for the toolbar.
     * @property {string} textHex - Hex color for text/icons.
     * @property {string} activeTabHex - Hex color for active tab/button background.
     * @property {string} inactiveTabHex - Hex color for inactive frame/tab.
     * @property {"solid"|"gradient"|"image"} bgType - Background type.
     * @property {string|null} solidBgHex - Hex color for solid NTP background, if used.
     * @property {boolean} hasBackgroundImage - Whether a background image will be packaged.
     */

    /**
     * Convert a hex color string (#RRGGBB or RRGGBB) to an RGB triplet.
     *
     * @param {string} hex - Hex color string.
     * @returns {number[]} RGB array [r, g, b] in [0..255].
     */
    function hexToRgb(hex) {
        const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex || "");
        return result
            ? [
                parseInt(result[1], 16),
                parseInt(result[2], 16),
                parseInt(result[3], 16),
            ]
            : [0, 0, 0];
    }

    /**
     * Sanitize a string into a safe filename.
     *
     * - Replaces invalid characters with underscores
     * - Collapses multiple underscores
     * - Trims leading/trailing underscores
     *
     * @param {string} name - Desired filename base.
     * @param {string} fallback - Used if `name` is empty.
     * @returns {string} Safe filename base (no extension added).
     */
    function sanitizeFilename(name, fallback) {
        const base = (name || fallback || "file").toString();
        return base
            .replace(/[^a-z0-9_-]/gi, "_")
            .replace(/_+/g, "_")
            .replace(/^_+|_+$/g, "");
    }

    /**
     * Build a Chrome Theme manifest (Manifest V3).
     *
     * @param {BuildThemeOptions} opts - Theme options.
     * @returns {object} Manifest JSON object (ready to stringify).
     */
    function buildChromeThemeManifest(opts) {
        const themeName = (opts && opts.themeName) || "My Custom Theme";

        const frameRGB = hexToRgb(opts.frameHex);
        const toolbarRGB = hexToRgb(opts.toolbarHex);
        const textRGB = hexToRgb(opts.textHex);
        const activeTabRGB = hexToRgb(opts.activeTabHex);
        const inactiveTabRGB = hexToRgb(opts.inactiveTabHex);

        /** @type {any} */
        const manifest = {
            manifest_version: 3,
            version: "1.0",
            name: themeName,
            description: "Custom theme generated by Theme Generator extension.",
            theme: {
                colors: {
                    frame: frameRGB,
                    frame_inactive: inactiveTabRGB,
                    toolbar: toolbarRGB,
                    tab_text: textRGB,
                    tab_background_text: textRGB,
                    bookmark_text: textRGB,
                    ntp_text: textRGB,
                    button_background: activeTabRGB,
                },
            },
        };

        if (opts.hasBackgroundImage) {
            manifest.theme.images = { theme_ntp_background: "background.png" };
            manifest.theme.properties = {
                ntp_background_alignment: "center",
                ntp_background_repeat: "no-repeat",
            };
            manifest.theme.colors.ntp_background = [255, 255, 255];
        } else if (opts.bgType === "solid" && opts.solidBgHex) {
            manifest.theme.colors.ntp_background = hexToRgb(opts.solidBgHex);
        }

        return manifest;
    }

    return {
        hexToRgb,
        sanitizeFilename,
        buildChromeThemeManifest,
    };
});
