/* themeUtils.js
 * UMD-style: works in browser (window.ThemeUtils) AND in Jest/Node (module.exports)
 */
(function (root, factory) {
    // Node / Jest
    // eslint-disable-next-line no-undef
    if (typeof module === "object" && module.exports) {
        // eslint-disable-next-line no-undef
        module.exports = factory();
    } else {
        // Browser / Extension
        root.ThemeUtils = factory();
    }
})(typeof self !== "undefined" ? self : this, function () {
    function hexToRgb(hex) {
        const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
        return result
            ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
            : [0, 0, 0];
    }

    // Option B: cleaner filenames (collapse underscores + trim)
    function sanitizeFilename(name, fallback) {
        const base = (name || fallback || "file").toString();
        return base
            .replace(/[^a-z0-9_-]/gi, "_") // Replace invalid characters
            .replace(/_+/g, "_")          // Collapse multiple underscores
            .replace(/^_+|_+$/g, "");     // Trim leading/trailing underscores
    }

    function buildChromeThemeManifest(opts) {
        const themeName = opts.themeName || "My Custom Theme";

        const frameRGB = hexToRgb(opts.frameHex);
        const toolbarRGB = hexToRgb(opts.toolbarHex);
        const textRGB = hexToRgb(opts.textHex);
        const activeTabRGB = hexToRgb(opts.activeTabHex);
        const inactiveTabRGB = hexToRgb(opts.inactiveTabHex);

        const manifest = {
            manifest_version: 3,
            version: "1.0",
            name: themeName,
            description: "Custom theme generated by Theme Generator extension.",
            theme: {
                colors: {
                    frame: frameRGB,
                    frame_inactive: inactiveTabRGB,
                    toolbar: toolbarRGB,
                    tab_text: textRGB,
                    tab_background_text: textRGB,
                    bookmark_text: textRGB,
                    ntp_text: textRGB,
                    button_background: activeTabRGB
                }
            }
        };

        if (opts.hasBackgroundImage) {
            manifest.theme.images = { theme_ntp_background: "background.png" };
            manifest.theme.properties = {
                ntp_background_alignment: "center",
                ntp_background_repeat: "no-repeat"
            };
            manifest.theme.colors.ntp_background = [255, 255, 255];
        } else if (opts.bgType === "solid" && opts.solidBgHex) {
            manifest.theme.colors.ntp_background = hexToRgb(opts.solidBgHex);
        }

        return manifest;
    }

    return {
        hexToRgb,
        sanitizeFilename,
        buildChromeThemeManifest
    };
});
