// Convert hex color to RGB array
function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : [0, 0, 0];
}

// Handle the "Confirm" Button
document.getElementById("confirmBtn").addEventListener("click", () => {
  const btn = document.getElementById("confirmBtn");
  const originalText = btn.textContent;

  const themeName = document.getElementById("themeName").value || "My Custom Theme";

  // Get RGB arrays from color picker values
  const frameRGB = hexToRgb(document.getElementById("frameColor").value);
  const toolbarRGB = hexToRgb(document.getElementById("toolbarColor").value);
  const bgRGB = hexToRgb(document.getElementById("bgColor").value);
  const textRGB = hexToRgb(document.getElementById("textColor").value);

  // Construct the theme manifest (this is the JSON structure Chromium needs)
  const manifest = {
    manifest_version: 3,
    version: "1.0",
    name: themeName,
    description: "Custom theme generated by extension.",
    theme: {
      colors: {
        frame: frameRGB,
        toolbar: toolbarRGB,
        ntp_background: bgRGB,
        ntp_text: textRGB,
        tab_text: textRGB,
        tab_background_text: [255, 255, 255],
        button_background: toolbarRGB
      }
    }
  };

  // Create the file as a blob URL
  const jsonString = JSON.stringify(manifest, null, 2);
  const blob = new Blob([jsonString], { type: "application/json" });
  const url = URL.createObjectURL(blob);

  // Use Chrome downloads API (more reliable than <a>.click in extension popups)
  btn.textContent = "Downloading...";
  btn.disabled = true;

  chrome.downloads.download(
    {
      url,
      filename: "manifest.json",
      saveAs: true
    },
    (downloadId) => {
      // Don't revoke immediately; give Chrome time to start the download
      setTimeout(() => URL.revokeObjectURL(url), 5000);

      if (chrome.runtime.lastError || !downloadId) {
        const msg = chrome.runtime.lastError?.message || "Download failed.";
        console.error("Download error:", msg);

        btn.textContent = "Download failed";
        setTimeout(() => {
          btn.textContent = originalText;
          btn.disabled = false;
        }, 2000);
        return;
      }

      btn.textContent = "✓ Download started";
      setTimeout(() => {
        btn.textContent = originalText;
        btn.disabled = false;
      }, 2000);
    }
  );
});
