// Convert hex color to RGB array
function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : [0, 0, 0];
}

// Handle the "Download" button
document.getElementById("confirmBtn").addEventListener("click", () => {
  const btn = document.getElementById("confirmBtn");

  const rawName = document.getElementById("themeName").value;
  const themeName = (rawName || "").trim() || "My Custom Theme";

  // Get RGB arrays from color picker values
  const frameRGB = hexToRgb(document.getElementById("frameColor").value);
  const toolbarRGB = hexToRgb(document.getElementById("toolbarColor").value);
  const bgRGB = hexToRgb(document.getElementById("bgColor").value);
  const textRGB = hexToRgb(document.getElementById("textColor").value);

  // Construct the theme manifest object
  const manifest = {
    manifest_version: 3,
    version: "1.0",
    name: themeName,
    description: "Custom theme generated by extension.",
    theme: {
      colors: {
        frame: frameRGB,
        toolbar: toolbarRGB,
        ntp_background: bgRGB,
        ntp_text: textRGB,
        tab_text: textRGB,
        tab_background_text: [255, 255, 255],
        button_background: toolbarRGB
      }
    }
  };

  // Create and download the file
  const jsonString = JSON.stringify(manifest, null, 2);
  const blob = new Blob([jsonString], { type: "application/json" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = "manifest.json";
  document.body.appendChild(a);
  a.click();

  // Cleanup
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  // Visual feedback
  btn.textContent = "✓ Manifest Downloaded";
  btn.disabled = true;

  setTimeout(() => {
    btn.textContent = "Download Theme Manifest";
    btn.disabled = false;
  }, 2000);
});
